
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int NUMBER = 12;
  public static final int STRING = 13;
  public static final int EOF = 0;
  public static final int OPERATOR = 2;
  public static final int RBRACKET = 6;
  public static final int WRITE = 9;
  public static final int error = 1;
  public static final int RPAREN = 4;
  public static final int IDENTIFIER = 11;
  public static final int END = 8;
  public static final int LBRACKET = 5;
  public static final int LPAREN = 3;
  public static final int BEGIN = 7;
  public static final int KEYWORD = 10;
  public static final int CHAR = 14;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "OPERATOR",
  "LPAREN",
  "RPAREN",
  "LBRACKET",
  "RBRACKET",
  "BEGIN",
  "END",
  "WRITE",
  "KEYWORD",
  "IDENTIFIER",
  "NUMBER",
  "STRING",
  "CHAR"
  };
}

